name: Veracode Test Branch


on:
  push:
    branches: [ veracode ]
  pull_request:
    branches: [ veracode ]


jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v2
        
      - name: Build with Maven # Compiling the .war binary from the checked out repo source code to upload to the scanner in the next step
        run: mvn -B package --file app/pom.xml
          
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.1
        with:
          appname: 'Verademo Getting Started'
          createprofile: true
          filepath: 'app/target/verademo.war'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          teams: "Demo Team"
          scantimeout: 15
#          createsandbox: 'true'
#          sandboxname: 'SANDBOXNAME'
#          exclude: '*.js'
#          include: '*.war'
#          criticality: 'VeryHigh'